# Generated by Django 4.2.13 on 2024-05-11 13:56

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_profile_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="adress",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="Token",
            new_name="token",
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, default="EG", max_length=2, null=True
            ),
        ),
    ]
